package DomainLayer;

public enum Product_Category {
    DAIRY_PRODUCTS,
    FROZEN_PRODUCTS,
    FRUITS_AND_VEGETABLES,
    CLEANING_PRODUCTS,
    DRINKS,
    DRIED_PRODUCTS,
    MEAT_PRODUCTS,
    MISCELLANEOUS
}
